#!/bin/bash
# Run sudo su
# ./factoryreset

echo "CydYnni Hub Factory reset script"

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root: sudo su ./factoryreset"
   exit 1
fi

rpi-rw

echo "deleting phpfina and phptimeseries data"
sudo rm -rf /home/pi/data/phpfina
sudo rm -rf /home/pi/data/phptimeseries

echo "creating new phpfina and phptimeseries folders"
sudo mkdir /home/pi/data/phpfina
sudo mkdir /home/pi/data/phptimeseries
sudo chown www-data:root /home/pi/data/phpfina
sudo chown www-data:root /home/pi/data/phptimeseries

echo "deleting mysql emoncms database"
mysql -u root -e "drop database emoncms" -pemonpimysql2016
echo "creating new mysql emoncms database"
mysql -u root -e "create database emoncms" -pemonpimysql2016

redis-cli "flushall"

rpi-ro
