#!/bin/bash
# Run sudo su
# ./factoryreset

echo "CydYnni Hub Factory reset script"

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root: sudo su ./factoryreset"
   exit 1
fi

#rpi-rw

echo "deleting phpfina and phptimeseries data"
sudo rm -rf /var/opt/emoncms/phpfina
sudo rm -rf /var/opt/emoncms/phptimeseries

echo "creating new phpfina and phptimeseries folders"
sudo mkdir /var/opt/emoncms/phpfina
sudo mkdir /var/opt/emoncms/phptimeseries
sudo chown www-data:root /var/opt/emoncms/phpfina
sudo chown www-data:root /var/opt/emoncms/phptimeseries

echo "deleting mysql emoncms database"
mysql -u root -e "drop database emoncms" -pemonpimysql2016
echo "creating new mysql emoncms database"
mysql -u root -e "create database emoncms" -pemonpimysql2016

redis-cli "flushall"

#rpi-ro
